### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by paulmillr** [brunch/eslint-brunch#11]
- [x] Allow to load `.eslintrc`s [in order](https://github.com/eslint/eslint/blob/master/lib/config/config-file.js)
- [x] Allow to load `package.json`'s eslint field
- [x] Allow to read brunch config's config field
- [x] Fix Brunch 2.9? API issue

**Comment by michaelhogg** [comment]
I've just submitted #12 which implements most of those items.

**Comment by spyl94** [comment]
Closing `eslint-brunch` works well on brunch 2.9.
