### ISSUE TITLE
Add support for eslint 4

### ISSUE THREAD

**Issue by Anaphase** [brunch/eslint-brunch#19]
Using eslint 4 doesn't seem to work, it throws a bunch of errors related to invalid rules and such. This is caused by the fact that the module is [locked into eslint 3](https://github.com/brunch/eslint-brunch/blob/96d13c0cd8401a112829ab7a0ebda9d2bd5c9bcb/package.json#L16).

Could you publish a new version of this module to NPM as version `3.13.0` with the `eslint@^3.0.0` dependency changed to `eslint@^4.0.0`? Version `3.12.0` would still support eslint 3.x for anyone still using it.

I'm happy to submit a PR if that's easier for you, but you'd still have to publish the new version to NPM unless you gave me access to the NPM package or something.

**Comment by shvaikalesh** [comment]
Hey @Anaphase, thanks for report.

We will make a version bump and a release within couple of days. I believe no PR is necessary -- releasing is the hard part.

**Comment by Anaphase** [comment]
Awesome, thanks!

**Comment by Anaphase** [comment]
@shvaikalesh any update on this?
